[package]
authors = ["The Nushell Project Developers"]
description = "Support for the SNUON format (NUON with raw strings)."
repository = "https://github.com/nushell/nushell/tree/main/crates/snuon"
edition = "2024"
license = "MIT"
name = "snuon"
version = "0.108.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nu-parser = { path = "../nu-parser" }
nu-protocol = { path = "../nu-protocol", default-features = false }
nu-engine = { path = "../nu-engine", default-features = false }
nu-utils = { path = "../nu-utils", default-features = false }

[dev-dependencies]
chrono = { workspace = true }

[lints]
workspace = true
